// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_ASP.Data;

#nullable disable

namespace Proiect_ASP1.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240108150437_2")]
    partial class _2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proiect_ASP.Models.Antrenor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("data_nastere")
                        .HasColumnType("datetime2");

                    b.Property<string>("nume_familie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trofee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("antrenors");
                });

            modelBuilder.Entity("Proiect_ASP.Models.Echipa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AntrenorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Data_Infiintare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localitate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AntrenorId")
                        .IsUnique();

                    b.ToTable("echipas");
                });

            modelBuilder.Entity("Proiect_ASP.Models.Jucator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ImpresarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("aparitii")
                        .HasColumnType("int");

                    b.Property<int>("goluri")
                        .HasColumnType("int");

                    b.Property<string>("nume_familie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImpresarId");

                    b.ToTable("jucators");
                });

            modelBuilder.Entity("Proiect_ASP.Models.echipa_cont_juc", b =>
                {
                    b.Property<Guid>("EchipaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JucatorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EchipaId", "JucatorId");

                    b.HasIndex("JucatorId");

                    b.ToTable("echipa_cont_juc");
                });

            modelBuilder.Entity("Proiect_ASP1.Models.Impresar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("jucatori_impresariati")
                        .HasColumnType("int");

                    b.Property<string>("nume_familie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("impresars");
                });

            modelBuilder.Entity("Proiect_ASP.Models.Echipa", b =>
                {
                    b.HasOne("Proiect_ASP.Models.Antrenor", "Antrenor")
                        .WithOne("Echipa")
                        .HasForeignKey("Proiect_ASP.Models.Echipa", "AntrenorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antrenor");
                });

            modelBuilder.Entity("Proiect_ASP.Models.Jucator", b =>
                {
                    b.HasOne("Proiect_ASP1.Models.Impresar", "Impresar")
                        .WithMany("jucators")
                        .HasForeignKey("ImpresarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impresar");
                });

            modelBuilder.Entity("Proiect_ASP.Models.echipa_cont_juc", b =>
                {
                    b.HasOne("Proiect_ASP.Models.Echipa", "Echipa")
                        .WithMany("echipa_Cont_Jucs")
                        .HasForeignKey("EchipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_ASP.Models.Jucator", "Jucator")
                        .WithMany("echipa_Cont_Jucs")
                        .HasForeignKey("JucatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Echipa");

                    b.Navigation("Jucator");
                });

            modelBuilder.Entity("Proiect_ASP.Models.Antrenor", b =>
                {
                    b.Navigation("Echipa")
                        .IsRequired();
                });

            modelBuilder.Entity("Proiect_ASP.Models.Echipa", b =>
                {
                    b.Navigation("echipa_Cont_Jucs");
                });

            modelBuilder.Entity("Proiect_ASP.Models.Jucator", b =>
                {
                    b.Navigation("echipa_Cont_Jucs");
                });

            modelBuilder.Entity("Proiect_ASP1.Models.Impresar", b =>
                {
                    b.Navigation("jucators");
                });
#pragma warning restore 612, 618
        }
    }
}
